version: '3.7'

services:
  database:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: postgres

  bast:
    build: .
    environment:
      DATABASE_URL: postgres://postgres:postgres@database/postgres
      SERVER_URL: bast
      PORT: 3333
      JWT_SECRET: secret
      RUST_LOG: actix_web=info
      APP_ADDRESS: http://localhost:3000
    ports:
      - 3333:3333